@authUser = {{ createUser.request.body.username }}
@authPass = {{ createUser.request.body.password }}
@idUser = {{ createUser.response.body.id }}
@idTask = {{ createTask.response.body.id }}

### Healthy Controller
GET http://localhost:8080/
Content-Type: application/json

###
# @name createUser
POST http://localhost:8080/users/
Content-Type: application/json

{
  "name": "Joelton Lino Luz",
  "username": "teste",
  "password": "12345"
}

###
# @name createTask
POST http://localhost:8080/tasks/
Content-Type: application/json
Authorization: Basic {{authUser}}:{{authPass}}

{
  "description": "Tarefa para gravar aula (SpringBoot)",
  "title": "Java SpringBoot jluz",
  "priority": "ALTA",
  "startAt": "2023-11-06T12:30:00",
  "endAt": "2024-11-06T12:30:00"
}

###
GET http://localhost:8080/tasks/
Content-Type: application/json
Authorization: Basic {{authUser}}:{{authPass}}

###
PUT http://localhost:8080/tasks/{{idTask}}
Content-Type: application/json
Authorization: Basic {{authUser}}:{{authPass}}

{
  "title": "ALTERADO"
}